# Generated by Django 5.2 on 2025-12-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='barkmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
