# Generated by Django 5.2 on 2025-12-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_authtokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtokenmodel',
            name='token_type',
            field=models.CharField(choices=[('access', 'Access'), ('refresh', 'Refresh')], default='access', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='authtokenmodel',
            unique_together={('user', 'token_type')},
        ),
    ]
