# Generated by Django 5.2 on 2025-12-10 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_authtokenmodel_token_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtokenmodel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='authtokenmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dogusermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogusermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
