# Generated by Django 5.2 on 2025-12-14 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_created_authtokenmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barkmodel',
            name='sniff_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserSniffModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sniffs', to='core.barkmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sniffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Sniff',
                'verbose_name_plural': 'User Sniffs',
                'unique_together': {('user', 'bark')},
            },
        ),
    ]
